### PR TITLE
add dash deps

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Came here as was getting some failures in https://github.com/conda-forge/jupyter-dash-feedstock/pull/5

Looking at https://github.com/plotly/dash/blob/dev/requires-install.txt there are some dash deps e.g. dash_html_components

### CODE REVIEW

**Comment by moorepants** [comment]
From what I understand these are now vendored in dash and we don't need them.

**Comment by raybellwaves** [comment]
can probably ignore goes back to https://github.com/plotly/dash-core-components/blob/dev/dash_core_components/__init__.py

**Comment by bandersen23** [comment]
This is a good idea! What we could do would be the following since dash is on 2.1 now:

1. Update the component feedstocks to be `>=2.0` as they are simply `==2.0` right now. This sets us up for the following step.
2. Add the component libraries to `run_constrained` as this would enforce the libraries to be installed at the correct version if a user requests them but doesn't explicitly require them. It's essentially like an _optional_ dependency then. 

Thoughts @raybellwaves and @moorepants? If you think it's a good idea, I can go forward and submit some PRs for all this.

**Comment by moorepants** [comment]
Is this trying to solve the issue that you may have the old dependency packages installed in an environment and they clash with the new dash install?

**Comment by moorepants** [comment]
I'm still confused though. I thought the dependencies are not packaged with dash. So when shouldn't have to maintain the old subpackages, right?

For the problem I mentioned about having the old packages in an environment. I haven't' had any trouble, dash updated fine in my base env. So is this an issue?

**Comment by bandersen23** [comment]
We don't have to maintain the sub packages anymore. Updating them to be `dash >=2.0` just ensures that if you download them you can still get `dash 2.1`. In a new environment, I was able to download `dash 2.0` and a really old version of `dash-core-components` accidentally, so the fix I'm proposing really just makes it a solid build and prevents any random errors. 

This would be the last change to the sub packages and they wouldn't require any further work.

**Comment by moorepants** [comment]
Got it. The `run_constrained` pieces seems like a good move.

**Pull request closed without merging**
